const articles: Article[] = [
    // article 1
    {
        id: 1,
        title: 'Let me hug you, and let us be warm together. It is really healing.',
        desc: '',
        tag: ['Every second counts', 'Healing', 'Cute cat'],
        dateTime: '2023-02-27 12:20',
        location: 'Guangdong',
        userId: 1,
        userName: 'Feifei Loves Cats',
        isFollow: false,
        avatarUrl: '/avatar/avatar_01.png',
        images: [
            '/article/article01/img_01.jpg',
            '/article/article01/img_02.jpg',
            '/article/article01/img_03.jpg',
            '/article/article01/img_04.jpg',
            '/article/article01/img_05.jpg',
        ],
        favoriteCount: 325,
        collectionCount: 166,
        isFavorite: false,
        isCollection: false,
        comments: [
            {
                userName: 'Little AA',
                avatarUrl: '/avatar/avatar_40.png',
                message: 'Oh my gosh, so cute!',
                dateTime: '2023-02-28 07:23',
                location: 'Nanning',
                favoriteCount: 12,
                isFavorite: false,
                children: [
                    {
                        userName: 'Feifei Loves Cats',
                        avatarUrl: '/avatar/avatar_01.png',
                        message: 'Thank you for your support~',
                        dateTime: '2023-02-28 08:23',
                        location: 'Guangdong',
                        favoriteCount: 3,
                        isFavorite: false,
                    },
                ],
            },
            {
                userName: 'Everyday Sweet',
                avatarUrl: '/avatar/avatar_39.png',
                message: 'So cute, I really want to have one. How do you raise such an adorable kitten? I want to buy one from you, please tell me how?',
                dateTime: '2023-02-28 09:09',
                location: 'Fujian',
                favoriteCount: 7,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Prince Xiaoxiao',
                avatarUrl: '/avatar/avatar_38.png',
                message: "I've been hurt, I won't believe in love anymore.",
                dateTime: '2023-02-28 11:11',
                location: 'Hebei',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Deep Blue',
                avatarUrl: '/avatar/avatar_37.png',
                message: 'Really so cute, I want to raise one',
                dateTime: '2023-02-28 11:34',
                location: 'Tianjin',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Look Ground',
                avatarUrl: '/avatar/avatar_36.png',
                message: 'Supporting you',
                dateTime: '2023-02-28 11:35',
                location: 'Nanjing',
                favoriteCount: 0,
                isFavorite: false,
                children: undefined,
            },
        ],
    },
    // article 2
    {
        id: 2,
        title: 'No wonder the recipe given by netizens is so fragrant, I was really mesmerized',
        desc: "If you don't know how to cook the eggs at home, you can try this sausage scrambled eggs.\nMy mom said it's surprisingly delicious.\nSpicy and satisfying, really appetizing. The method is simple; you guys should give it a try too.",
        tag: ['Dinner', 'Homestyle Dish', 'Sausage Scrambled Eggs', 'Egg Recipes'],
        dateTime: '2023-02-28 09:21',
        location: 'Guangxi',
        userId: 2,
        userName: 'Chef Little Dumbo',
        isFollow: false,
        avatarUrl: '/avatar/avatar_02.png',
        images: [
            '/article/article02/img_01.jpg',
            '/article/article02/img_02.jpg',
            '/article/article02/img_03.jpg',
            '/article/article02/img_04.jpg',
            '/article/article02/img_05.jpg',
        ],
        favoriteCount: 1098,
        collectionCount: 208,
        isFavorite: false,
        isCollection: false,
        comments: [
            {
                userName: 'Fat Fat Fat',
                avatarUrl: '/avatar/avatar_40.png',
                message: "Definitely following, this blogger's dishes truly look delicious. Learning to cook with them every day, I'm going to become a chef, haha~",
                dateTime: '2023-02-28 07:23',
                location: 'Chengdu',
                favoriteCount: 45,
                isFavorite: false,
                children: [
                    {
                        userName: 'Feifei Loves Cats',
                        avatarUrl: '/avatar/avatar_01.png',
                        message: "Get on it; this method is very simple~",
                        dateTime: '2023-02-28 13:23',
                        location: 'Guangdong',
                        favoriteCount: 1,
                        isFavorite: false,
                    },
                ],
            },
            {
                userName: 'Left Half',
                avatarUrl: '/avatar/avatar_39.png',
                message: 'Looks really appetizing',
                dateTime: '2023-02-28 09:09',
                location: 'Fujian',
                favoriteCount: 2,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'TTTi',
                avatarUrl: '/avatar/avatar_38.png',
                message: 'This looks tastier than what I make',
                dateTime: '2023-02-28 11:11',
                location: 'Henan',
                favoriteCount: 3,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'One Clothes',
                avatarUrl: '/avatar/avatar_37.png',
                message: "I'll make this dish tomorrow, and also make some broccoli",
                dateTime: '2023-02-28 11:34',
                location: 'Tianjin',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Faint',
                avatarUrl: '/avatar/avatar_36.png',
                message: 'Looks so delicious',
                dateTime: '2023-02-28 11:35',
                location: 'Anhui',
                favoriteCount: 0,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'TyTyTy',
                avatarUrl: '/avatar/avatar_36.png',
                message: 'Is this easy to make? I want to learn',
                dateTime: '2023-02-28 11:35',
                location: 'Henan',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Ma Dafa 11',
                avatarUrl: '/avatar/avatar_36.png',
                message: "This is so delicious, I'll have an extra bowl of rice tonight",
                dateTime: '2023-02-28 11:35',
                location: 'Beijing',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
        ],
    },
    // article 3
    {
        id: 3,
        title: 'When I woke up, the orange tree had climbed up to my window',
        desc: 'I had a dream about California. I dreamed that when I woke up from the dream, the orange tree had climbed up to my window.',
        tag: ['Aesthetic Accumulation', '365-Day Photography Plan', 'Los Angeles', 'Filter and Color Grading', 'Healing Scenery', 'Mobile Wallpaper'],
        dateTime: '2023-02-28 16:00',
        location: 'USA',
        userId: 3,
        userName: 'Little Kite',
        isFollow: false,
        avatarUrl: '/avatar/avatar_03.png',
        images: [
            '/article/article03/img_01.jpg',
            '/article/article03/img_02.jpg',
            '/article/article03/img_03.jpg',
            '/article/article03/img_04.jpg',
        ],
        favoriteCount: 18700,
        collectionCount: 2088,
        isFavorite: false,
        isCollection: false,
        comments: [
            {
                userName: 'ABC',
                avatarUrl: '/avatar/avatar_35.png',
                message: 'Suddenly thought of that cologne, the citrus-scented "California Summer"',
                dateTime: '2023-02-28 07:23',
                location: 'Chengdu',
                favoriteCount: 45,
                isFavorite: false,
                children: [
                    {
                        userName: 'Little Kite',
                        avatarUrl: '/avatar/avatar_03.png',
                        message: 'I actually have that one',
                        dateTime: '2023-02-28 13:23',
                        location: 'USA',
                        favoriteCount: 1,
                        isFavorite: false,
                    },
                ],
            },
            {
                userName: 'Fairy',
                avatarUrl: '/avatar/avatar_34.png',
                message: 'This is so "Call Me by Your Name"',
                dateTime: '2023-02-28 09:09',
                location: 'Fujian',
                favoriteCount: 2,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Chery',
                avatarUrl: '/avatar/avatar_33.png',
                message: "I've followed you on Weibo; didn't expect to see you on Xiaohongshu as well",
                dateTime: '2023-02-28 11:11',
                location: 'Henan',
                favoriteCount: 3,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Shiyu',
                avatarUrl: '/avatar/avatar_32.png',
                message: 'Originally had bad emotions, but seeing this scenery made me feel much better',
                dateTime: '2023-02-28 11:34',
                location: 'Shandong',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Pineapple',
                avatarUrl: '/avatar/avatar_31.png',
                message: 'Ahhh, so beautiful! I declare this will be my next phone wallpaper',
                dateTime: '2023-02-28 11:35',
                location: 'Shanghai',
                favoriteCount: 0,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Look Ground',
                avatarUrl: '/avatar/avatar_30.png',
                message: 'I can already smell the fresh scent of oranges',
                dateTime: '2023-02-28 11:35',
                location: 'Henan',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Biss',
                avatarUrl: '/avatar/avatar_29.png',
                message: 'So beautiful, can I get the original image?',
                dateTime: '2023-02-28 11:35',
                location: 'Beijing',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
        ],
    },
    // article 4
    {
        id: 4,
        title: 'A bed full of clear dreams presses down the Milky Way',
        desc: 'The distant little boat is getting closer\nThe oars stir the lake, creating ripples\nSparkling under the sunlight\nPainting the spring picture in my heart',
        tag: ['Healing Images', 'Healing Scenery', 'Notebook Inspiration', 'Photography', 'Spring'],
        dateTime: '2023-03-03 11:00',
        location: 'Zhejiang',
        userId: 4,
        userName: 'Amnesia',
        isFollow: false,
        avatarUrl: '/avatar/avatar_04.png',
        images: [
            '/article/article04/img_01.jpg',
            '/article/article04/img_02.jpg',
            '/article/article04/img_03.jpg',
            '/article/article04/img_04.jpg',
        ],
        favoriteCount: 8700,
        collectionCount: 288,
        isFavorite: true,
        isCollection: false,
        comments: [
            {
                userName: 'Indecisive',
                avatarUrl: '/avatar/avatar_28.png',
                message: "I saved the picture; I'm going to use it as my phone wallpaper",
                dateTime: '2023-02-28 07:23',
                location: 'Zhejiang',
                favoriteCount: 45,
                isFavorite: false,
                children: [
                    {
                        userName: 'Amnesia',
                        avatarUrl: '/avatar/avatar_04.png',
                        message: 'Sure thing~',
                        dateTime: '2023-02-28 13:23',
                        location: 'Zhejiang',
                        favoriteCount: 1,
                        isFavorite: false,
                    },
                ],
            },
            {
                userName: 'Diao Diao',
                avatarUrl: '/avatar/avatar_27.png',
                message: 'Which camera did you use? This is so beautiful',
                dateTime: '2023-02-28 09:09',
                location: 'Fujian',
                favoriteCount: 2,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Wind Wind',
                avatarUrl: '/avatar/avatar_26.png',
                message: 'Is this West Lake?',
                dateTime: '2023-02-28 11:11',
                location: 'Henan',
                favoriteCount: 3,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Yu Sang',
                avatarUrl: '/avatar/avatar_25.png',
                message: "Wow, I've seen this picture several times; is this the original creator?",
                dateTime: '2023-03-04 11:34',
                location: 'Shandong',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Mushroom',
                avatarUrl: '/avatar/avatar_24.png',
                message: 'So beautiful',
                dateTime: '2023-02-28 11:35',
                location: 'Shanghai',
                favoriteCount: 0,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Coal Ball',
                avatarUrl: '/avatar/avatar_23.png',
                message: 'So beautiful',
                dateTime: '2023-02-28 11:35',
                location: 'Henan',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Dust',
                avatarUrl: '/avatar/avatar_22.png',
                message: 'Wow, your photography skills are great',
                dateTime: '2023-02-28 11:35',
                location: 'Beijing',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
        ],
    },
    // article 5
    {
        id: 5,
        title: 'The stars captured with a phone, didn’t expect so many people to like it',
        desc: 'March\nHundreds of flowers bloom\nThe red leaf plum took the lead\nIt becomes more crystal clear at night\nScattered in the air\nJust like stars\nStanding under a canopy of flowers',
        tag: ['Photography', 'Chengdu', 'iPhone', 'Spring', 'March'],
        dateTime: '2023-03-03 11:00',
        location: 'Chengdu',
        userId: 5,
        userName: 'Slowly',
        isFollow: false,
        avatarUrl: '/avatar/avatar_05.png',
        images: [
            '/article/article05/img_01.jpg',
            '/article/article05/img_02.jpg',
            '/article/article05/img_03.jpg',
            '/article/article05/img_04.jpg',
            '/article/article05/img_05.jpg',
            '/article/article05/img_06.jpg',
            '/article/article05/img_07.jpg',
        ],
        favoriteCount: 2655,
        collectionCount: 288,
        isFavorite: false,
        isCollection: false,
        comments: [
            {
                userName: 'Heart Matters',
                avatarUrl: '/avatar/avatar_22.png',
                message: "My sister posted the same picture in her moments; it's really beautiful. Missing home even more today.",
                dateTime: '2023-02-28 07:23',
                location: 'Jiangxi',
                favoriteCount: 12,
                isFavorite: false,
                children: [
                    {
                        userName: 'Slowly',
                        avatarUrl: '/avatar/avatar_05.png',
                        message: 'Hugs to you',
                        dateTime: '2023-02-28 13:23',
                        location: 'Chengdu',
                        favoriteCount: 1,
                        isFavorite: false,
                    },
                ],
            },
            {
                userName: 'Mumu',
                avatarUrl: '/avatar/avatar_21.png',
                message: "These aren't stars; they're clearly my dreams",
                dateTime: '2023-02-28 09:09',
                location: 'Fujian',
                favoriteCount: 2,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: "You are Back",
                avatarUrl: '/avatar/avatar_20.png',
                message: 'Could you please provide a tutorial?',
                dateTime: '2023-02-28 11:11',
                location: 'Henan',
                favoriteCount: 3,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'The Wind Rises',
                avatarUrl: '/avatar/avatar_19.png',
                message: 'She has many more pictures on her homepage',
                dateTime: '2023-03-04 11:34',
                location: 'Shandong',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Mountain Mist',
                avatarUrl: '/avatar/avatar_18.png',
                message: 'What kind of flower is this?',
                dateTime: '2023-02-28 11:35',
                location: 'Shanghai',
                favoriteCount: 0,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Xinxin',
                avatarUrl: '/avatar/avatar_17.png',
                message: 'Why did I think of "Water Cloud Sky"?',
                dateTime: '2023-02-28 11:35',
                location: 'Henan',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Huanhuan',
                avatarUrl: '/avatar/avatar_16.png',
                message: "I will ll go take pictures when the pear blossoms bloom",
                dateTime: '2023-02-28 11:35',
                location: 'Beijing',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
        ],
    },
    // article 6
    {
        id: 6,
        title: 'Confessions are like the wind in the fields roaring in youth',
        desc: "This time I'm not climbing trees but going down to the fields.\nTurns out I still like myself with short hair.\nSpring has arrived in Dali.\nThere are vast fields of rapeseed flowers and vegetable fields.\nSeeing the wind blow over the wheat waves in person makes me feel so free.\nThe clouds are also beautiful.",
        tag: ['Portrait', 'Girl Portrait', 'Variety of Posing', 'Short Hair', 'Youth'],
        dateTime: '2023-03-03 11:00',
        location: 'Yunnan',
        userId: 6,
        userName: 'Xiaoxiao',
        isFollow: false,
        avatarUrl: '/avatar/avatar_06.png',
        images: [
            '/article/article06/img_01.jpg',
            '/article/article06/img_02.jpg',
            '/article/article06/img_03.jpg',
            '/article/article06/img_04.jpg',
            '/article/article06/img_05.jpg',
        ],
        favoriteCount: 2655,
        collectionCount: 288,
        isFavorite: false,
        isCollection: false,
        comments: [
            {
                userName: 'Little Cat Jia Jia',
                avatarUrl: '/avatar/avatar_15.png',
                message: 'The first photo is really beautiful',
                dateTime: '2023-02-28 07:23',
                location: 'Jiangxi',
                favoriteCount: 112,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Songhe Xiaodengbao',
                avatarUrl: '/avatar/avatar_14.png',
                message: 'The first picture is so stunning, full of freedom and youthful spirit',
                dateTime: '2023-02-28 09:09',
                location: 'Yunnan',
                favoriteCount: 23,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Walk Walk 123',
                avatarUrl: '/avatar/avatar_13.png',
                message: 'Hello, can I use this picture as my avatar?',
                dateTime: '2023-02-28 11:11',
                location: 'Henan',
                favoriteCount: 3,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Want to See You a',
                avatarUrl: '/avatar/avatar_12.png',
                message: 'Everything grows freely, and youth rustles in the wilderness.',
                dateTime: '2023-03-04 11:34',
                location: 'Yunnan',
                favoriteCount: 5,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Tian Zi Ge',
                avatarUrl: '/avatar/avatar_11.png',
                message: "I especially love watching Hayao Miyazaki's animations and the girls in them. Their body proportions are just like yours. I once thought they were just animated characters, but seeing your first picture finally made me understand that art comes from life.",
                dateTime: '2023-02-28 11:35',
                location: 'Shandong',
                favoriteCount: 1112,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Wasdbbb',
                avatarUrl: '/avatar/avatar_10.png',
                message: 'At first glance, I thought it was a Hayao Miyazaki animation',
                dateTime: '2023-02-28 11:35',
                location: 'Henan',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Autumn Leaves',
                avatarUrl: '/avatar/avatar_09.png',
                message: 'The first picture is so beautiful, I want to use it as my avatar',
                dateTime: '2023-02-28 11:35',
                location: 'Beijing',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
        ],
    },
    // article 7
    {
        id: 7,
        title: 'Those healing sentences that touch the heart',
        desc: 'The little boat disappears from now on, entrusting the rest of my life to rivers and seas.\nLucky to meet you with a face like peach blossoms; since then, the paths are full of warm spring.\nWhen you reach the end of the water, sit and watch the clouds rise.\nFlowers bloom and fall in due time; meeting and parting happen by chance.\nPatiently wait for a tree to bloom, hoping you will return when the leaves fall.',
        tag: ['Classical Poetry', 'Stunning', 'Notes', 'Inspiration'],
        dateTime: '2023-03-04 12:00',
        location: 'Shandong',
        userId: 7,
        userName: 'Qing Yuan',
        isFollow: false,
        avatarUrl: '/avatar/avatar_07.png',
        images: [
            '/article/article07/img_01.jpg',
            '/article/article07/img_02.jpg',
            '/article/article07/img_03.jpg',
            '/article/article07/img_04.jpg',
            '/article/article07/img_05.jpg',
        ],
        favoriteCount: 1998,
        collectionCount: 233,
        isFavorite: false,
        isCollection: false,
        comments: [],
    },
    // article 8
    {
        id: 8,
        title: 'Private movie list: 32 literary films suitable for watching alone',
        desc: "I'm Qian Duoduo, and this is Qian Duoduo's Dry Goods Shop.\nFocused on sharing dry goods in various fields.\nIn the vast sea of people, it's fate that we meet, so please like, follow, and collect.\nLet's work together to become even better.",
        tag: ['Notebook Inspiration', 'Stress Relief Tips', 'High-Scoring Movies', 'Movie Recommendations', 'Female Growth'],
        dateTime: '2023-03-04 15:00',
        location: 'Yunnan',
        userId: 8,
        userName: 'Xiaoxiao',
        isFollow: true,
        avatarUrl: '/avatar/avatar_08.png',
        images: [
            '/article/article08/img_01.jpg',
            '/article/article08/img_02.jpg',
            '/article/article08/img_03.jpg',
            '/article/article08/img_04.jpg',
            '/article/article08/img_05.jpg',
        ],
        favoriteCount: 2655,
        collectionCount: 288,
        isFavorite: false,
        isCollection: false,
        comments: [
            {
                userName: 'Jiang Min',
                avatarUrl: '/avatar/avatar_06.png',
                message: 'The "Three Colors" trilogy should be on your list',
                dateTime: '2023-02-28 07:23',
                location: 'Shanghai',
                favoriteCount: 8,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Klok',
                avatarUrl: '/avatar/avatar_05.png',
                message: 'Wong Kar-wai, Hou Hsiao-hsien, and Ang Lee are also great',
                dateTime: '2023-02-28 09:09',
                location: 'Yunnan',
                favoriteCount: 23,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Huanhuan',
                avatarUrl: '/avatar/avatar_04.png',
                message: 'The movie "Spring, Summer, Fall, Winter... and Spring"',
                dateTime: '2023-02-28 11:11',
                location: 'Henan',
                favoriteCount: 3,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Wild',
                avatarUrl: '/avatar/avatar_03.png',
                message: '"Inside Llewyn Davis" is really good!',
                dateTime: '2023-03-04 11:34',
                location: 'Yunnan',
                favoriteCount: 5,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Slide',
                avatarUrl: '/avatar/avatar_02.png',
                message: 'Your movie list is really good; all of them are great films worth watching multiple times. Support!',
                dateTime: '2023-02-28 11:35',
                location: 'Shandong',
                favoriteCount: 1112,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Sweater',
                avatarUrl: '/avatar/avatar_01.png',
                message: "Once there was a sincere love in front of me, but I didn't cherish it. I regretted it only after losing it.",
                dateTime: '2023-02-28 11:35',
                location: 'Henan',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
        ],
    },
    // article 9
    {
        id: 9,
        title: 'Fairytale-like spring in Suffolk, England',
        desc: 'Vast grasslands\nVintage buildings\nBeautiful environment\nFresh air',
        tag: ['Romantic Life', 'Notebook Inspiration', 'Life Aesthetics', 'Countryside Life', 'English Countryside', 'Pastoral Style', 'Pastoral Life', 'Countryside Cottage', 'Fairytale Style'],
        dateTime: '2023-03-05 12:12',
        location: 'UK',
        userId: 9,
        userName: 'StiffKit',
        isFollow: true,
        avatarUrl: '/avatar/avatar_09.png',
        images: [
            '/article/article09/img_01.jpg',
            '/article/article09/img_02.jpg',
            '/article/article09/img_03.jpg',
            '/article/article09/img_04.jpg',
            '/article/article09/img_05.jpg',
            '/article/article09/img_06.jpg',
            '/article/article09/img_07.jpg',
        ],
        favoriteCount: 1244,
        collectionCount: 260,
        isFavorite: false,
        isCollection: false,
        comments: [
            {
                userName: 'Stack',
                avatarUrl: '/avatar/avatar_40.png',
                message: 'A dreamy place',
                dateTime: '2023-02-28 07:23',
                location: 'Shanghai',
                favoriteCount: 8,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Little Shuangshuang',
                avatarUrl: '/avatar/avatar_39.png',
                message: 'The fewer people there are, the more it feels like a fairy tale',
                dateTime: '2023-03-05 13:09',
                location: 'Yunnan',
                favoriteCount: 23,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Hawaii Breeze',
                avatarUrl: '/avatar/avatar_38.png',
                message: 'This is the life I yearn for',
                dateTime: '2023-03-05 11:11',
                location: 'Henan',
                favoriteCount: 3,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Comfortable',
                avatarUrl: '/avatar/avatar_37.png',
                message: 'So wonderful',
                dateTime: '2023-03-04 11:34',
                location: 'Yunnan',
                favoriteCount: 5,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'JoJo',
                avatarUrl: '/avatar/avatar_36.png',
                message: 'This color tone is so beautiful!',
                dateTime: '2023-03-05 11:35',
                location: 'Shandong',
                favoriteCount: 1112,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Book Grass',
                avatarUrl: '/avatar/avatar_35.png',
                message: 'I really like this place; I want to move there',
                dateTime: '2023-02-28 11:35',
                location: 'Henan',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
        ],
    },
    // article 10
    {
        id: 10,
        title: 'Sunlight pours into the house; may you be awakened by sunshine every morning',
        desc: 'David Steindl-Rast said that if you want to live a life full of positive energy, express gratitude directly to prolong happiness. People are not grateful because they are happy; they are happy because they are grateful. Every day, wake up to greet the rising sun, watch the sun rise and set, feel the different temperatures and atmospheres of each season; every day is unique.\nIn a room filled with sunlight, watching flowers bloom and fall outside the window, clouds rolling and unfolding, burn incense, brew tea, hold a book, and enjoy the leisurely time under the warm winter sun.',
        tag: [ 'Romantic Life', 'Notebook Inspiration', 'Illustration Sharing', 'Inspirational Positivity', 'English Countryside', 'Pastoral Style', 'Pastoral Life', 'Countryside Cottage', 'Fairytale Style' ],
        dateTime: '2023-03-05 12:12',
        location: 'Guangdong',
        userId: 10,
        userName: 'Xiaoxiao Momo',
        isFollow: true,
        avatarUrl: '/avatar/avatar_10.png',
        images: [
            '/article/article10/img_01.jpg',
            '/article/article10/img_02.jpg',
            '/article/article10/img_03.jpg',
            '/article/article10/img_04.jpg',
            '/article/article10/img_05.jpg',
            '/article/article10/img_06.jpg',
            '/article/article10/img_07.jpg',
        ],
        favoriteCount: 3044,
        collectionCount: 1200,
        isFavorite: false,
        isCollection: false,
        comments: [
            {
                userName: 'Er Er',
                avatarUrl: '/avatar/avatar_34.png',
                message: "Can't help but like it, it's really beautiful",
                dateTime: '2023-02-28 07:23',
                location: 'Shanghai',
                favoriteCount: 8,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Yoyo',
                avatarUrl: '/avatar/avatar_33.png',
                message: 'Illustrators nowadays are getting more and more amazing',
                dateTime: '2023-03-05 13:09',
                location: 'Yunnan',
                favoriteCount: 23,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Super',
                avatarUrl: '/avatar/avatar_32.png',
                message: 'Is that firewood in the oven?',
                dateTime: '2023-03-05 11:11',
                location: 'Henan',
                favoriteCount: 3,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Little Maple',
                avatarUrl: '/avatar/avatar_31.png',
                message: "Although AI illustrations are strong, I still prefer those drawn by people; there's a soul in them",
                dateTime: '2023-03-04 11:34',
                location: 'Yunnan',
                favoriteCount: 5,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Little Monster',
                avatarUrl: '/avatar/avatar_30.png',
                message: 'Haha, I really like this place',
                dateTime: '2023-03-05 11:35',
                location: 'Shandong',
                favoriteCount: 1112,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Blueberry',
                avatarUrl: '/avatar/avatar_29.png',
                message: "This kind of environment is made for fairies",
                dateTime: '2023-02-28 11:35',
                location: 'Henan',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
        ],
    } // (The rest of the articles would continue here with all Chinese text translated into English)
];

export default articles;
