const goods: GoodsSimple[] = [
    {
        id: 1,
        title: 'Pure Wheat Flour, Gluten-Free, Low-Fat, Mixed Grains, Sugar-Friendly, Avocado Hashimoto · 700g * 3 Bags',
        image: '/goods/goods01/img_01.jpg',
        price: 51,
        originPrice: undefined,
        promotion: undefined,
    },
    {
        id: 2,
        title: 'Brown Rice Noodles, Jiangxi Rice Noodles, Nancang Mixed Noodles, Snail Noodles 800g, Whole Grains, Gluten-Free',
        image: '/goods/goods02/img_01.jpg',
        price: 84,
        originPrice: undefined,
        promotion: undefined,
    },
    {
        id: 3,
        title: 'Handmade Yiming Zen Collection 9.9r New Soft Wrap Bracelet 12mm Round Beads Matcha Cheese Collection',
        image: '/goods/goods03/img_01.jpg',
        price: 9.9,
        originPrice: 12.8,
        promotion: undefined,
    },
    {
        id: 4,
        title: 'Hickory Nut Bracelet, Antique Walnut Bracelet, Handheld Bead String, Small Walnut String, Handheld, Bursting Juice, Collected from Deep Mountains',
        image: '/goods/goods04/img_01.jpg',
        price: 9.9,
        originPrice: undefined,
        promotion: undefined,
    },
    {
        id: 5,
        title: 'Pure Solid Color Beads 5.6R Fast Hand Competition · Pure Green 11*12mm',
        image: '/goods/goods05/img_01.jpg',
        price: 5.8,
        originPrice: undefined,
        promotion: undefined,
    },
    {
        id: 6,
        title: 'Natural Green Sandalwood Buddhist Bead Bracelet, Old Material Hetian Jade, Sandalwood Chain, Ethnic Ornaments for Men and Women',
        image: '/goods/goods06/img_01.jpg',
        price: 12,
        originPrice: undefined,
        promotion: undefined,
    },
    {
        id: 7,
        title: 'Butter Coconut Vegetarian Crisp Salted Egg Yolk Crispy Biscuits, Coconut Pastry Snacks, So Crisp No Friends, Coffee Coconut Crisp',
        image: '/goods/goods07/img_01.jpg',
        price: 15.8,
        originPrice: undefined,
        promotion: 'Save 18 when you spend over 100',
    },
    {
        id: 8,
        title: 'Thick-Cut Toast Bread, Milk Flavor, Tiramisu Flavor, Hand-Torn Bread, 14 Bags, Mixed Flavors',
        image: '/goods/goods08/img_01.jpg',
        price: 19.9,
        originPrice: 25.98,
        promotion: undefined,
    },
    {
        id: 9,
        title: 'Psyllium Husk Powder Pack, Dietary Fiber, Keto Baking, Gluten-Free, Zero Fat, 250g * 2 Bags',
        image: '/goods/goods09/img_01.jpg',
        price: 76,
        originPrice: undefined,
        promotion: 'Save 50 when you spend over 240',
    },
    {
        id: 10,
        title: 'Guangxi Lipu Fruit Water Chestnuts, Seasonal Snacks, Vegetables, Guaranteed Fresh, Wholesale Price, Free Shipping, 5 Near the King of Kings',
        image: '/goods/goods10/img_01.jpg',
        price: 75,
        originPrice: undefined,
        promotion: undefined,
    },
    {
        id: 11,
        title: 'Summer Washed Pure Cotton Solid Color Japanese Baseball Cap, Unisex, Black, Korean Soft Brim Cap, Army Green Adjustable',
        image: '/goods/goods11/img_01.jpg',
        price: 14,
        originPrice: 18.8,
        promotion: undefined,
    },
    {
        id: 12,
        title: 'Pure Cinnamon Powder 65g, Natural Seasoning, Beverage, Baking, Fitness Latte, Golden Milk Tea Hashimoto 65g * 2 Bottles',
        image: '/goods/goods12/img_01.jpg',
        price: 29,
        originPrice: undefined,
        promotion: undefined,
    },
    {
        id: 13,
        title: 'Sakura Shrimp Rice Crackers, Non-Fried Grain Rice Crackers, Crispy Spicy Flavor',
        image: '/goods/goods13/img_01.jpg',
        price: 11.8,
        originPrice: undefined,
        promotion: undefined,
    },
    {
        id: 14,
        title: 'Mango Milk Cake, Strawberry Dried Love, Nougat Marshmallow, Dried Mango, Recommended for Mango Lovers',
        image: '/goods/goods14/img_01.jpg',
        price: 38.6,
        originPrice: undefined,
        promotion: undefined,
    },
    {
        id: 15,
        title: 'Premium Gourd · Available in Live Stream',
        image: '/goods/goods15/img_01.jpg',
        price: 9.9,
        originPrice: undefined,
        promotion: undefined,
    },
    {
        id: 16,
        title: 'Natural Bodhi Bracelet, Three-Top Bodhi Root Cultural Play Female Buddhist Bead Bracelet, Milk Mango 12*11mm',
        image: '/goods/goods16/img_01.jpg',
        price: 19.9,
        originPrice: undefined,
        promotion: undefined,
    },
    {
        id: 17,
        title: 'Old Beijing Donkey Roll Glutinous Rice Cake, Northeastern Specialty Bean Noodle Roll, Instant Snacks, 450g',
        image: '/goods/goods17/img_01.jpg',
        price: 14.9,
        originPrice: 19.9,
        promotion: undefined,
    },
    {
        id: 18,
        title: 'Audis Cocoa Butter Original Dark Chocolate Almond Filled Chocolate, Pure Handmade Baking, Internet Famous Snack, Original Square',
        image: '/goods/goods18/img_01.jpg',
        price: 10.8,
        originPrice: 12.98,
        promotion: undefined,
    },
    {
        id: 19,
        title: 'Light Summer Slow Carb Package, Whole Wheat Buckwheat Noodles, Chicken Breast Meatballs, Whole Wheat Bread, Black Coffee, Sausage',
        image: '/goods/goods19/img_01.jpg',
        price: 39.9,
        originPrice: undefined,
        promotion: undefined,
    },
    {
        id: 20,
        title: '[Set of 2] Modern Simple Embossed Glass Vase, Transparent Flower Arrangement Vase, Glacier Pattern',
        image: '/goods/goods20/img_01.jpg',
        price: 9.9,
        originPrice: undefined,
        promotion: undefined,
    },
];

export const top10Category = [
    { id: 1, name: 'Trendy Buyers Store', image: '/goods/top10/top1.jpg' },
    { id: 2, name: 'New Trends', image: '/goods/top10/top2.jpg' },
    { id: 3, name: 'Benefit Club', image: '/goods/top10/top3.jpg' },
    { id: 4, name: 'Little Oasis', image: '/goods/top10/top4.jpg' },
    { id: 5, name: 'Treasure Good Shop', image: '/goods/top10/top5.jpg' },
    { id: 6, name: 'Unique Design', image: '/goods/top10/top6.jpg' },
    { id: 7, name: 'Ballet Style Girl', image: '/goods/top10/top7.jpg' },
    { id: 8, name: 'Quiet Tea and Wood Fragrance', image: '/goods/top10/top8.jpg' },
    { id: 9, name: 'Spring Outing Essentials', image: '/goods/top10/top9.jpg' },
    { id: 10, name: 'Youth Travel', image: '/goods/top10/to10.jpg' },
];

export default goods;
